/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as WardRouteImport } from './routes/ward'
import { Route as ComplaintIdRouteImport } from './routes/complaint.$id'
import { Route as WardIdRouteImport } from './routes/ward.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const WardRoute = WardRouteImport.update({
  id: '/ward',
  path: '/ward',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintIdRoute = ComplaintIdRouteImport.update({
  id: '/complaint/$id',
  path: '/complaint/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WardIdRoute = WardIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/ward': typeof WardRouteWithChildren
  '/complaint/$id': typeof ComplaintIdRoute
  '/ward/$id': typeof WardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/ward': typeof WardRouteWithChildren
  '/complaint/$id': typeof ComplaintIdRoute
  '/ward/$id': typeof WardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/ward': typeof WardRouteWithChildren
  '/complaint/$id': typeof ComplaintIdRoute
  '/ward/$id': typeof WardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/privacy' | '/ward' | '/complaint/$id' | '/ward/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/privacy' | '/ward' | '/complaint/$id' | '/ward/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/privacy'
    | '/ward'
    | '/complaint/$id'
    | '/ward/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  WardRoute: typeof WardRouteWithChildren
  ComplaintIdRoute: typeof ComplaintIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ward': {
      id: '/ward'
      path: '/ward'
      fullPath: '/ward'
      preLoaderRoute: typeof WardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaint/$id': {
      id: '/complaint/$id'
      path: '/complaint/$id'
      fullPath: '/complaint/$id'
      preLoaderRoute: typeof ComplaintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ward/$id': {
      id: '/ward/$id'
      path: '/$id'
      fullPath: '/ward/$id'
      preLoaderRoute: typeof WardIdRouteImport
      parentRoute: typeof WardRoute
    }
  }
}

interface WardRouteChildren {
  WardIdRoute: typeof WardIdRoute
}

const WardRouteChildren: WardRouteChildren = {
  WardIdRoute: WardIdRoute,
}

const WardRouteWithChildren = WardRoute._addFileChildren(WardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  WardRoute: WardRouteWithChildren,
  ComplaintIdRoute: ComplaintIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
